/*
 * Certificates Mutations Types
 * The mutations types available for the Certificates module.
 */

export const CREATE_CERTIFICATE = 'CREATE_CERTIFICATE'
export const DELETE_CERTIFICATE = 'DELETE_CERTIFICATE'
export const UPDATE_CERTIFICATE = 'UPDATE_CERTIFICATE'
export const FETCH_CERTIFICATES_SUCCESS = 'FETCH_CERTIFICATES_SUCCESS'
export const FETCH_CERTIFICATE_ID = 'FETCH_CERTIFICATE_ID'

export default {
  CREATE_CERTIFICATE,
  DELETE_CERTIFICATE,
  UPDATE_CERTIFICATE,
  FETCH_CERTIFICATES_SUCCESS,
  FETCH_CERTIFICATE_ID
}
